spring:
  application:
    name: financecontrol
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    port: 8080
